receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  filter/drop_healthcheck:
    spans:
      exclude:
        match_type: strict
        attributes:
          - key: http.target
            value: "/admin/restricted-word/healthcheck"
  filter/drop_healthcheck_v2:
    spans:
      exclude:
        match_type: strict
        attributes:
          - key: http.route
            value: "/admin/restricted-word/healthcheck"

  filter/drop_ELB_HealthChecker:
    spans:
      exclude:
        match_type: strict
        attributes:
          - key: http.user_agent
            value: "ELB-HealthChecker/2.0"

exporters:
  awscloudwatchlogs:
    log_group_name: "/ecs/search-service-cidev/otel/restricted-word-web-log"
    log_stream_name: "testing-integrations-stream"
  awsxray:
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces,filter/drop_ELB_HealthChecker]
      exporters: [debug,awsxray]
    logs:
      receivers: [otlp]
      exporters: [awscloudwatchlogs]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]