receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

  filter/drop_healthcheck_attributes:
    traces:
      span:
        - 'IsMatch(attributes["url.path"], ".*healthcheck.*")'
        - 'IsMatch(attributes["http.target"], ".*healthcheck.*")'
        - 'IsMatch(attributes["http.route"], ".*healthcheck.*")'

exporters:
  awscloudwatchlogs:
    log_group_name: "/ecs/search-service-cidev/restricted-word-web-otel-log"
    log_stream_name: "otel-integrations-stream"
  awsxray:
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces,filter/drop_healthcheck_attributes]
      exporters: [debug,awsxray]
    logs:
      receivers: [otlp]
      exporters: [awscloudwatchlogs]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]